### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by AlexanderMisel** [Leaflet/Leaflet.VectorGrid#253]
```
> leaflet.vectorgrid@1.3.0 build /home/paws/Leaflet.VectorGrid
> gobble build -f dist/

gobble: build started
gobble: 01-rollup done in 1250ms
gobble: 03-merge done in 40ms
∙∙∙◦∙∙∙ 05-rollup running...
gobble: 05-rollup transformation failed

input:  /home/paws/Leaflet.VectorGrid/.gobble-build/03-merge/1
output: /home/paws/Leaflet.VectorGrid/.gobble-build/05-rollup/1
>>>
Could not resolve './slicerWebWorker.js.worker' from /home/paws/Leaflet.VectorGrid/.gobble-build/03-merge/1/Leaflet.VectorGrid.Slicer.js
Error: Could not resolve './slicerWebWorker.js.worker' from /home/paws/Leaflet.VectorGrid/.gobble-build/03-merge/1/Leaflet.VectorGrid.Slicer.js
    at /home/paws/Leaflet.VectorGrid/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:139:17
    at load (/home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:156:43)
    at onex (/home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:181:17)
    at /home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:15:69
    at callback (/home/paws/Leaflet.VectorGrid/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:153:21)
<<<


gobble: 05-rollup transformation failed

input:  /home/paws/Leaflet.VectorGrid/.gobble-build/03-merge/1
output: /home/paws/Leaflet.VectorGrid/.gobble-build/05-rollup/1
>>>
Could not resolve './slicerWebWorker.js.worker' from /home/paws/Leaflet.VectorGrid/.gobble-build/03-merge/1/Leaflet.VectorGrid.Slicer.js
Error: Could not resolve './slicerWebWorker.js.worker' from /home/paws/Leaflet.VectorGrid/.gobble-build/03-merge/1/Leaflet.VectorGrid.Slicer.js
    at /home/paws/Leaflet.VectorGrid/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:139:17
    at load (/home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:156:43)
    at onex (/home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:181:17)
    at /home/paws/Leaflet.VectorGrid/node_modules/resolve/lib/async.js:15:69
    at callback (/home/paws/Leaflet.VectorGrid/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:153:21)
<<<

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leaflet.vectorgrid@1.3.0 build: `gobble build -f dist/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leaflet.vectorgrid@1.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paws/.npm/_logs/2020-12-16T03_31_24_844Z-debug.log
```

**Comment by jayvarner** [comment]
I am only able to install dependencies and build using Node 8 and Python 2.7

**Comment by deniial00** [comment]
Has anyone upgraded the dependencies of the bundleing-process? They seem heavily outdated. I am still not able to bundle and build. I tried installing the dependencies via node8 but no luck same with node20 and node22
```
npm error path C:\Users\USER\Documents\dev\leaflet-vector-grid\Leaflet.VectorGrid\node_modules\mmmagic
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.15.0 | win32 | x64
npm error gyp info find Python using Python version 3.12.3 found at "C:\Program Files\Python312\python.exe"
npm error gyp info find VS using VS2022 (17.10.35013.160) found at:
npm error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Program Files\Python312\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'C:\\Users\\USER\\scoop\\apps\\nodejs-lts\\20.15.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\USER\\Documents\\dev\\leaflet-vector-grid\\Leaflet.VectorGrid\\node_modules\\mmmagic\\build\\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\USER\\scoop\\apps\\nodejs-lts\\20.15.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\USER\\AppData\\Local\\node-gyp\\Cache\\20.15.0\\include\\node\\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\\Users\\USER\\AppData\\Local\\node-gyp\\Cache\\20.15.0',
npm error gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\USER\\scoop\\apps\\nodejs-lts\\20.15.0\\node_modules\\npm\\node_modules\\node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\USER\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.15.0\\\\<(target_arch)\\\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=C:\\Users\\USER\\Documents\\dev\\leaflet-vector-grid\\Leaflet.VectorGrid\\node_modules\\mmmagic',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'C:\\Users\\USER\\Documents\\dev\\leaflet-vector-grid\\Leaflet.VectorGrid\\node_modules\\mmmagic\\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error node:internal/modules/cjs/loader:1148
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module 'nan'
npm error Require stack:
npm error - C:\Users\USER\Documents\dev\leaflet-vector-grid\Leaflet.VectorGrid\node_modules\mmmagic\[eval]
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
npm error     at Module._load (node:internal/modules/cjs/loader:986:27)
npm error     at Module.require (node:internal/modules/cjs/loader:1233:19)
npm error     at require (node:internal/modules/helpers:179:18)
npm error     at [eval]:1:1
npm error     at runScriptInThisContext (node:internal/vm:209:10)
npm error     at node:internal/process/execution:118:14
npm error     at [eval]-wrapper:6:24
npm error     at runScript (node:internal/process/execution:101:62)
npm error     at evalScript (node:internal/process/execution:133:3) {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: [
npm error     'C:\\Users\\USER\\Documents\\dev\\leaflet-vector-grid\\Leaflet.VectorGrid\\node_modules\\mmmagic\\[eval]'
npm error   ]
npm error }
npm error
npm error Node.js v20.15.0
npm error gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\USER\scoop\apps\nodejs-lts\20.15.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:297:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm error gyp ERR! System Windows_NT 10.0.22631
npm error gyp ERR! command "C:\\Users\\USER\\scoop\\apps\\nodejs-lts\\current\\node.exe" "C:\\Users\\USER\\scoop\\apps\\nodejs-lts\\20.15.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm error gyp ERR! cwd C:\Users\USER\Documents\dev\leaflet-vector-grid\Leaflet.VectorGrid\node_modules\mmmagic
npm error gyp ERR! node -v v20.15.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
```
