### ISSUE TITLE
how i can test branch make-interactive

### ISSUE THREAD

**Issue by gornak49** [Leaflet/Leaflet.VectorGrid#26]
Can your help me, please!

I want to test branch make-interactive.
I work in Win7:
1)I instal msysgit
2)git clone git://github.com/Leaflet/Leaflet.VectorGrid.git
3)cd Leaflet.VectorGrid
4)git checkout make-interactive

how can I build Leaflet.VectorGrid.bundled.js, and view demo?

**Comment by IvanSanchez** [comment]
https://github.com/Leaflet/Leaflet.VectorGrid#developing , then `npm start`, then point a browser to `http://localhost:4567`.

Feel free to send a PR to add this bit of info to the readme

**Comment by gornak49** [comment]
Sorry, but I have same problems with npm install:

```
[npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN optional dep failed, continuing fsevents@1.0.14

> runas@3.1.1 install C:\Users\gis\Leaflet.VectorGrid\node_modules\gobble-cli\no
de_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

\
C:\Users\gis\Leaflet.VectorGrid\node_modules\gobble-cli\node_modules\pathwatcher
\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Program Files\n
odejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy
p.js" rebuild )  else (node "" rebuild )
C:\Users\gis\Leaflet.VectorGrid\node_modules\gobble-cli\node_modules\pathwatche
r\node_modules\runas\build\binding.sln : error MSB3411: не удалось загрузить ко
мпонент "VCBuild.exe" для Visual C++. Если компонент не установлен, 1) установк
а Microsoft Windows SDK для Windows Server 2008 и .NET Framework 3.5, 2) устано
вка Microsoft Visual Studio 2008
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gis\Leaflet.VectorGrid\node_modules\gobble-cli\node_module
s\pathwatcher\node_modules\runas
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gis\Leaflet.VectorGrid\npm-debug.log]
```

**Comment by gornak49** [comment]
install node-gyp,

but have problem with:
npm start 
```
> leaflet.vectorgrid@1.0.1 start C:\Users\gis\Leaflet.VectorGrid
> gobble


gobble: error starting gobble
>>>
Cannot find module './get-source-node'
Error: Cannot find module './get-source-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\gis\Leaflet.VectorGrid\node_modules\gobble-c
oncat\gobble-concat.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
